#!/usr/bin/with-contenv bash

cd /chiadog || exit 1

# set timezone
# shellcheck disable=SC2154
if [[ -n "${TZ}" ]]; then
  echo "Setting timezone to ${TZ}"
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi

# start application
# shellcheck disable=SC1091
. ./venv/bin/activate

exec \
s6-setuidgid abc python3 main.py --config /config/config.yaml
